version: '3'
services:
# we create two containers with the same setup in Dockerfile.dev
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    # we supply a new set of commands for the tests container 
    command: ["npm", "run", "test"]
